### ISSUE TITLE
add obmenu-generator in menu

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#18]
We will install this package next time but do we need to make a menu for it.
Will this not conflict with the standard menu.xml. Can users get back to the standard menu once they started obmenu-generator... I do not think so. I believe it will make a backup file but even then. There is no menu/script that changes it back from the obmenu-generated menu to the standard.

Further study is required before including in menu

**Comment by Dobbie03** [comment]
I think for the newer user this could cause more issues than it will solve.  I would prefer that the user decides on whether they install this item or not.

I don't want this included in +4.  If someone can provide a good enough reason I will rethink my stand.

**Comment by erikdubois** [comment]
Let us not included it yet. We have other issues on our hands. Maybe next release.

**Comment by erikdubois** [comment]
deleted the menu!!
