### ISSUE TITLE
add keyboard shortcut Super + L

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#19]
activates slimlock
[http://archlabs.prophpbb.com/topic82.html](http://archlabs.prophpbb.com/topic82.html)

**Comment by Dobbie03** [comment]
We will need to add slim and slim-themes to the package list.  I have made a customer ARCHLabs branded Slim theme.

**Comment by erikdubois** [comment]
where are these themes ? @osgyan will need these to build his iso

**Comment by Dobbie03** [comment]
Slim-themes are in the main Arch repos. I have uploaded my custom theme to GitHub

**Comment by erikdubois** [comment]
can you re-edit and include link? Do not see Main Arch repo? Clear for you but not for me...

**Comment by Dobbie03** [comment]
Will update tomorrow evening.

**Comment by erikdubois** [comment]
this looks to me the link 
[https://github.com/ARCHLabs/Slimlock-Theme](https://github.com/ARCHLabs/Slimlock-Theme)

**Comment by Dobbie03** [comment]
Yes that's my custom ArchLabs theme. Sorry I thought you meant a link for the slim-themes package.

**Comment by erikdubois** [comment]
commited
