### ISSUE TITLE
rc.xlm - add keyboard shortcuts for window management/tiling

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#2]
Add win+keypad 1 2 3 4 5 6 7 8 9 to move the windows to top left, top right etc...

[http://archlabs.prophpbb.com/topic80.html](http://archlabs.prophpbb.com/topic80.html)

**Comment by Dobbie03** [comment]
Erik, please proceed.  If you could confirm that the Display Keybinds entry updates to match the changes please.

**Comment by erikdubois** [comment]
ok but what does this mean  " If you could confirm that the Display Keybinds entry updates to match the changes please."

**Comment by Dobbie03** [comment]
In the help menu there is a entry to display the keybinds either in the obmenu or a separate window. I'm not sure if this automatically update when changes are made to the rc.

**Comment by erikdubois** [comment]
yes it does

**Comment by Dobbie03** [comment]
Okay I'll mark this one closed.

**Comment by erikdubois** [comment]
reopened this issue - it is still on the to do list I think

**Comment by Dobbie03** [comment]
Good point.

**Comment by erikdubois** [comment]
committed
