### ISSUE TITLE
dmenu keybindings

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#20]
keep referring to a script or put code in rc.xml

[http://archlabs.prophpbb.com/topic82.html](http://archlabs.prophpbb.com/topic82.html)
dmenu_run -i -nb '#151617' -nf '#d8d8d8' -sb '#d8d8d8' -sf '#151617' -fn 'NotoMonoRegular:bold:pixelsize=14'

**Comment by erikdubois** [comment]
[http://archlabs.prophpbb.com/topic61.html](http://archlabs.prophpbb.com/topic61.html)

**Comment by Dobbie03** [comment]
Please proceed with this Erik.

**Comment by erikdubois** [comment]
ok

**Comment by erikdubois** [comment]
added a keybind key
    <keybind key="A-F3">
       <action name="Execute">
        <command>dmenu_run -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=12'</command>
      </action>
    </keybind>

Font can be changed if you want to...
