### ISSUE TITLE
exo-preferred-application

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#21]
add to menu
[http://archlabs.prophpbb.com/topic66.html](http://archlabs.prophpbb.com/topic66.html)

**Comment by Dobbie03** [comment]
Erik, please proceed with updating the menu.xml with exo-preferred rather than the fixed application.
https://github.com/ARCHLabs/Openbox-Configs/blob/master/menu.xml

**Comment by erikdubois** [comment]
ok

**Comment by erikdubois** [comment]
@osgyan hi did you add exo-open to the list of applications 
needed for this issue to work

**Comment by erikdubois** [comment]
@osgyan you should close this one once you have added exo-application on your iso.

**Comment by erikdubois** [comment]
installed in ARCHLabs 3.2.1 closing
