### ISSUE TITLE
Arch scripts in menu

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#26]
Links to all the sh files - i believe I read it had to go? Am i wrong in this?

<menu id="install" label="ARCHLabs Extras One-By-One">
				<separator label="Install OBO Scripts"/>
				<item label="Install Audacious Player">
				<action name="Execute">
					<execute>termite -e /usr/bin/audacious.sh</execute>
				</action>
			</item>
				<item label="Install Audacity">
				<action name="Execute">
					<execute>termite -e /usr/bin/audacity.sh</execute>
				</action>
			</item>
				<item label="Install Blender">
				<action name="Execute">
					<execute>termite -e /usr/bin/blender.sh</execute>
				</action>
			</item>

**Comment by Dobbie03** [comment]
menu.xml has been updated with the changes.  Install scripts have been removed.
