### ISSUE TITLE
get rid of extra line in pipemenu help

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#30]
there is a seperator just under the title that does need to be there
![get-rid-of seperator](https://cloud.githubusercontent.com/assets/10594806/24017814/c784e814-0a91-11e7-8724-489d70bb5e80.png)

**Comment by Dobbie03** [comment]
I don't know where that separator is coming from.

**Comment by erikdubois** [comment]
I do
Found it in the piping menu for printing 
From.memory i think /usr/bin

**Comment by Dobbie03** [comment]
Excellent.  I looked there but I must have missed it.

Mark this one closed?

**Comment by Dobbie03** [comment]
I don't have this replicated separator line on my AL install on the laptop.

**Comment by Dobbie03** [comment]
Can anyone else please confirm this otherwise I will close as solved.

**Comment by Dobbie03** [comment]
Erik, do you still have this extra line?

**Comment by erikdubois** [comment]
@toola69 Brett, I think you installed version 3.1. Can you confirm the line is there or can we close this?

**Comment by Dobbie03** [comment]
I'm closing this.  Can be reopened if issue persists for others.
