### ISSUE TITLE
Menu structure of next release

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#31]
I have already expressed the concern that we should make a menu we (the four of us) will actually use.
(kill nemo excluded)
Just wanted to share and show my current setup. It might give you an idea how to proceed. 
I would use the names of the applications not browser but firefox. Vivaldi is becoming increasing popular. It loads websites suuuuper fast. I am only waiting for all my extensions to be compatible and I do my move to vivaldi.
Less seperator titles  - I know nice in design - darker background (e.g. online help)
I think I added programming to the list of categories.
Well you see my menu's and as you know they are on my github.
![menustructure-erik](https://cloud.githubusercontent.com/assets/10594806/24018317/adec1786-0a93-11e7-9f34-2b975c380502.gif)

**Comment by Dobbie03** [comment]
I agree with this, Erik if you could go ahead and commit the changes please.

**Comment by erikdubois** [comment]
First we have todecide what the menu should be like
What to include and what not?

**Comment by toola69** [comment]
We will all have to talk because if we are changing then we are stepping away from bunsenlabs or crunchbang on Arch. This was the whole idea of this distro. I don't care which way it goes but if we are going to break out and totally change the distro then maybe we need to rethink the name and breakaway from the bunsenlabs moniker...

**Comment by Dobbie03** [comment]
In my mind the menu is a minor issue, the look is there, which is the main thing.

Let's discuss further on Hangouts.

**Comment by Dobbie03** [comment]
Issue partially resolved 

Continue here
https://github.com/ARCHLabs/Openbox-Configs/issues/32
