### ISSUE TITLE
Menu Structure 

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Openbox-Configs#32]
decide on a menu structure the four of us will work with in the future (a compromise) else we will work with our own menu's and everybody else with our menu from iso -- we will get questions we can not answer since we are not using the standard menu

**Comment by Dobbie03** [comment]
I have had a good think on this.

What I would like is the basic layout that we have already to be kept as is.  

For the additions proposed by @erikdubois, I would prefer sub-menus rather than additions to the main menu of obmenu.  I want to keep the look as close as possible to the original Bunsen look.

Thoughts, team?

**Comment by erikdubois** [comment]
there are some menu's i rather not have on the 4th level or more -- three levels down is enough for me
like restart of openbox
or 
like restart of compositor

**Comment by Dobbie03** [comment]
Four is the maximum I'd like to go, unless we are some sort of special menu like the Network one I have on my custom AL build on my PC.

**Comment by erikdubois** [comment]
I think we should decide on the menu and applications as soon as possible, together with their keyboard shortcuts and the extra software that we will need to put on the iso.
the menu has repercussions in many files

**Comment by Dobbie03** [comment]
Yes it does.  I am about to fire up my laptop and start working on these menus.

**Comment by erikdubois** [comment]
super

**Comment by erikdubois** [comment]
any insight on the menu's... are they finished?

**Comment by Dobbie03** [comment]
Yes I have updated and tested the refined menus. Closing.

**Comment by erikdubois** [comment]
ok will check them today
