### ISSUE TITLE
Include the latest updated themes from Bunsen

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Openbox-Configs#34]
Need to add the new and improved GTK3 themes from BunsenLabs, also remove old deprecated themes.

**Comment by Dobbie03** [comment]
Forked from hhhorb's repo.  Not sure if we are allowed to rename these? 
@erikdubois @toola69

**Comment by Dobbie03** [comment]
Need to close this repo I'm guessing as hhh's themes are superior to the Oomox based ones.

https://github.com/ARCHLabs/Themes.git

**Comment by erikdubois** [comment]
You know my vision. Unless we have someone capable of understanding current gtk and future gtk versions, I would spend no time on this and make minor adjustments on the gtk theme of Horst3180 aka the arc theme.

**Comment by Dobbie03** [comment]
Basically what we need to do to keep the look is to include the themes that the BL guys come up with.  Also for a bit of variety let's include Arc.

**Comment by erikdubois** [comment]
fine by me

**Comment by erikdubois** [comment]
but i do feel some kind of "chain" in your reply
but again fine by me

**Comment by Dobbie03** [comment]
I'm not sure what you mean by "chain"

I'd like to see the default theme as Bunsen-He.

**Comment by erikdubois** [comment]
you want to stick to the look of bunsenlab
fine by me
closing this
