### ISSUE TITLE
Include cbatticon

### ISSUE THREAD

**Issue by Dobbie03** [ARCHLabs/Openbox-Configs#35]
With fdpowermon being basically dead I looked into other options for keeping an eye on your laptop battery and came across cbatticon.

It does nothing other than monitor your charge level.  There are no options or anything.  Worth including?

@erikdubois @toola69 @ajjames31

**Comment by toola69** [comment]
This sound good to me brother.

**Comment by Dobbie03** [comment]
Just found that XFCE4 Power Monitor actually has decided to work correctly so maybe we could stick with that?

**Comment by erikdubois** [comment]
best to stick with software that will be supported in future
I would have gone to xfce too. Their software can run on its own without installing the complete desktop.

**Comment by Dobbie03** [comment]
Xfxe4 power monitor it is then
