### ISSUE TITLE
pipemenus.rc

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#43]
do we need this file? 
usage?

**Comment by Dobbie03** [comment]
Can you link me to it @erikdubois

**Comment by erikdubois** [comment]
this is the link
[https://github.com/ARCHLabs/Openbox-Configs/blob/master/pipemenus.rc](https://github.com/ARCHLabs/Openbox-Configs/blob/master/pipemenus.rc)

**Comment by Dobbie03** [comment]
I don't think this is required.  Delete please.
