### ISSUE TITLE
change menu : typo gtk-recordMyDesktop

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#5]
change in menu from gtk-recordmydesktop to gtk-recordMyDesktop

**Comment by erikdubois** [comment]
This issue has been merged.
Check out github.... some changes. 
If anyone has more experience using github, please change. 
Just using my common-sense.
All forum topics - bug and tips have been incorporated
With the @ sign you can communicate with each other - or with the whole team
 @ARCHLabs/core-members

**Comment by Dobbie03** [comment]
I had already made the change in my updated configs.
