### ISSUE TITLE
screenshots error

### ISSUE THREAD

**Issue by erikdubois** [ARCHLabs/Openbox-Configs#9]
screenshots in menu refer to a directory Screenshots
without creating it you get errors
suggestion : get rid of this folder and use standard Pictures
decision required

[http://archlabs.prophpbb.com/topic50.html](http://archlabs.prophpbb.com/topic50.html)

**Comment by Dobbie03** [comment]
Directory updated to Pictures.

Also added a screenshot with selection entry.
